### ISSUE TITLE
AArch64 Linux?

### ISSUE THREAD

**Issue by jonahnm** [Picovoice/picollm#35]
Attempts to run the python picoLLM demo results in an unsupported CPU error. Is it possible to add support for AArch64 on Linux?

**Comment by ErisMik** [comment]
Please reopen this issue using the issue template, otherwise I cannot assist you: 

https://github.com/Picovoice/picollm/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=picoLLM+Issue%3A+
