### ISSUE TITLE
picoLLM Issue: GPU not supported in the Android SDK.

### ISSUE THREAD

**Issue by jonahnm** [Picovoice/picollm#37]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice picoLLM docs
- [X] I have searched the existing issues for picoLLM

### SDK

Android

### picoLLM package version

1.0.0

### Framework version

N/A

### Platform

Android

### OS/Browser version

Android 14.0

### Describe the bug

Attempting to use device string 'gpu' on the Android platform results in an error stating that only 'cpu' and 'best' are supported on Android.

### Steps To Reproduce

1. Add `setDevice("gpu")` to `PicoLLM.builder` in the Android demo.
2. Run and load model, observe the error.

### Expected Behavior

The model runs on the GPU, without throwing an error message.

**Comment by jonahnm** [comment]
(Will also add that the documentation states the Android SDK supports GPU)

**Comment by matt200-ok** [comment]
Hello @jonahnm, unfortunately we do not currently support GPU on Android.
