### ISSUE TITLE
picoLLM Issue: Unable to load PLLM model in Picollm Node Demo

### ISSUE THREAD

**Issue by AlphaBlackout** [Picovoice/picollm#42]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice picoLLM docs
- [X] I have searched the existing issues for picoLLM

### SDK

Node.js

### picoLLM package version

1.0.1

### Framework version

Node.js v20.15.1

### Platform

Windows (x86_64)

### OS/Browser version

Windows 10

### Describe the bug

In attempting to run the picollm-chat-demo for nodejs, an exception is thrown when attempting open/load the downloaded pllm model file:

> node:internal/modules/cjs/loader:1454
  return process.dlopen(module, path.toNamespacedPath(filename));
                           ^

>Error: The specified module could not be found.
\\?\C:\Users\***\AppData\Roaming\npm\node_modules\@picovoice\picollm-node-demo\node_modules\@picovoice\picollm-node\lib\windows\amd64\pv_picollm.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at new PicoLLM (C:\Users\***\AppData\Roaming\npm\node_modules\@picovoice\picollm-node-demo\node_modules\@picovoice\picollm-node\dist\picollm.js:61:27)
    at completionDemo (C:\Users\***\AppData\Roaming\npm\node_modules\@picovoice\picollm-node-demo\chat.js:153:19)
    at Object.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\@picovoice\picollm-node-demo\chat.js:207:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) {
  code: 'ERR_DLOPEN_FAILED'
}

I confirmed that the file path was correct using fs.existsSync and FileExplorer with testing llama-2-7b-chat-269.pllm and phi2-290.pllm with both resulting in the above exception. Also confirmed by putting in an invalid path and receiving a "File not found at 'modelPath'" exception instead. I'm fairly certain that the demo sees the file but just unable to load it.

I did see a similar issue reported regarding the Android implementation of picollm, but had not been resolved yet.

### Steps To Reproduce

1. Install picollm demo for nodejs: npm install -g @picovoice/picollm-node-demo
2. Download chat compatible pllm file from picovoice (I tested llama-2-7b-chat-269.pllm and phi2-290.pllm with same result)
3. Run the picollm demo: picollm-chat-demo --access_key "${VALID_ACCESS_KEY}" --model_path "${VALID_MODEL_PATH}" --prompt "What is 5 * 6?"
4. There should be the exception as a result of running Step 3.

### Expected Behavior

Expected to receive a response akin to "The answer is 30." back from the picollm node demo based on the prompt "What is 5 * 6?".

**Comment by mrrostam** [comment]
Thank you for reporting the issue. We’ve been able to recreate the problem and are currently working on a solution. We will notify you here as soon as the fix is implemented and the new package is available.

**Comment by mrrostam** [comment]
@AlphaBlackout, could you try the [new release demo package](https://www.npmjs.com/package/@picovoice/picollm-node-demo) and see if it resolves the issue you were encountering?"

**Comment by matt200-ok** [comment]
@AlphaBlackout, the [new released demo package](https://www.npmjs.com/package/@picovoice/picollm-node-demo) should resolve the issue. Please confirm if the demo is now working for you.
