### ISSUE TITLE
Add Phi-3.5-mini-instruct

### ISSUE THREAD

**Issue by niutech** [Picovoice/picollm#48]
Please add the latest [Phi-3.5-mini-instruct](https://huggingface.co/microsoft/Phi-3.5-mini-instruct) model to PicoLLM, which is much better than Phi-2.

**Comment by matt200-ok** [comment]
Hello @niutech, adding Phi-3.5-mini-instruct is on our roadmap but I don't have an estimate for when it will be finished.

**Comment by matt200-ok** [comment]
Hello @niutech, Phi-3.5-mini-instruct has been added to PicoLLM and is usable with the 1.2 version of the sdk.

**Comment by niutech** [comment]
@matt200-ok Fantastic! Thank you!
