### ISSUE TITLE
Picovoice Console Issue: NotImplementedError: Unsupported CPU: '0xd42'.

### ISSUE THREAD

**Issue by donato-barossi** [Picovoice/picollm#49]
I'm trying to implement a porcupine wake word in python (version Python 3.8.10) on a Jetson Orin NANO (64-bit ARM architecture) but I have this issue "NotImplementedError: Unsupported CPU: '0xd42'" when try to import the library (import pvporcupine)

**Comment by laves** [comment]
That's correct, we don't support that platform
