### ISSUE TITLE
Add support for llama 3.2 1b it and 3.2 3b it

### ISSUE THREAD

**Issue by bsudharsan-amalgam** [Picovoice/picollm#68]
These models are amazing and ideally suited for picovoice llm. Would be good to get this in picovoice format or a transform code that can convert these models in hf in 4 bit to the picovoice format. Thanks so much!

**Comment by ErisMik** [comment]
Hello @bsudharsan-amalgam , we will consider adding `llama 3.2` models to our roadmap but unfortunately I don't have any estimates for when it will be finished.

**Comment by bsudharsan-amalgam** [comment]
Thanks @ErisMik 

Is there a converter code or so that safetensor files or gguf files for 1b can be converted and tested? Kindly let me know if there's something we can do to help in interim. Thanks again for the excellent engine!

**Comment by ErisMik** [comment]
Sorry, we don't have any way for you to convert from another format to the Picovoice format at this time.

**Comment by matt200-ok** [comment]
We have just released version 1.2.3 of picoLLM which has added support for llama 3.2
